version: "3.7"

services:
  todo_postgres:
    image: postgres:13-alpine
    container_name: todo_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todos
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - todo-postgres-data:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

  todo_server:
    build:
      context: packages/server
      dockerfile: Dockerfile.dev
    container_name: todo_server
    ports:
      - "8000:8000"
    depends_on:
      - todo_postgres
    environment:
      DATABASE_URL: postgresql://root:password@todo_postgres:5432/todos
      SECRET_KEY: some_secret_key_that_you_need_to_change
    volumes:
      - ./packages/server/src:/app/src
    networks:
      - default

volumes:
  todo-postgres-data:

networks:
  default:
