version: "3.7"

services:
  todo_postgres:
    image: postgres:13-alpine
    container_name: todo_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todos
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - todo-postgres-data:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

volumes:
  todo-postgres-data:

networks:
  default:
